apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: stable-diffusion-hf
  namespace: diffusion
spec:
  name: diffusion
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: diffusion
          image: <repository URL>/diffusion:v0.1
    graph:
      name: diffusion
    name: default
    replicas: 1